metrics:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
    remote_write:
        - url: ${GRAFANA_PROMETHEUS_URL}
          basic_auth:
            username: ${GRAFANA_PROMETHEUS_USERNAME}
            password: ${GRAFANA_CLOUD_KEY}
    external_labels:
      service: ${RAILWAY_SERVICE_NAME}
      replica: ${RAILWAY_REPLICA_ID}

  configs:
    - name: default
      scrape_configs:
        - job_name: 'app'
          static_configs:
            - targets: ['localhost:${PORT}']

        # - job_name: 'node-exporter'
        #   static_configs:
        #     - targets: ['localhost:9100']

# Logs configuration to read from /var/log
logs:
  configs:
    - name: system-logs
      positions:
        filename: "/tmp/positions.yaml"
      clients:
        - url: ${GRAFANA_LOKI_URL}
          basic_auth:
            username: ${GRAFANA_LOKI_USERNAME}
            password: ${GRAFANA_CLOUD_KEY}
      scrape_configs:
        - job_name: 'system'
          static_configs:
            - targets: ['localhost']
              labels:
                job: "goapp"
                service: ${RAILWAY_SERVICE_NAME}
                replica: ${RAILWAY_REPLICA_ID}
                __path__: "/var/log/goapp.log"