server:
  log_level: info

# metrics:
#   global:
#     scrape_interval: 1m
#     remote_write:
#       - url: http://localhost:9009/api/prom/push
#   configs:
#     - name: default
#       scrape_configs:
#         - job_name: agent
#           static_configs:
#             - targets: ['127.0.0.1:12345']

logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:514
            labels:
              job: "syslog"
          relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: 'host'
    clients:
      - url: https://859230:${GRAFANA_API_KEY}@logs-prod-006.grafana.net/loki/api/v1/push

# traces:
#   configs:
#   - name: default
#     receivers:
#       jaeger:
#         protocols:
#           grpc: # listens on the default jaeger grpc port: 14250
#     remote_write:
#       - endpoint: localhost:55680
#         insecure: true  # only add this if TLS is not required
#     batch:
#       timeout: 5s
#       send_batch_size: 100

# integrations:
#   node_exporter:
#     enabled: true